### ISSUE TITLE
error: stdsimd and paru-2.0.1-1

### ISSUE THREAD

**Issue by TheDarrenS** [nosvagor/dotfiles#7]
Hey Nosvagor,
To give you a quick word. I am just starting to learn all this and linux is somewhat newish. 
Im in my 50s and with autism. So if you could bare with me.  I always seem to want to do the hardthings first :)

Anywho here is a error when running these commands
```

git clone https://github.com/nosvagor/dotfiles
paru -S --needed - < ~/dotfiles/etc/packages.lst

```

```
error[E0635]: unknown feature `stdsimd`
  --> /home/thedarrens/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.3/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

   Compiling raur v7.0.0
For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'paru-2.0.1-1': 
```

**Comment by cogikyo** [comment]
hmm, looks like a failure to build paru for some reason. 

these dotfiles are old. I haven't updated in quite some time as my new work wouldn't allow me to use my Linux machine. 

I would not suggest following my instructions as of now to try and replicate what I have, probably multiple issues.

If anything, use these reference to understand what tools you might need yourself and follow the relevant projects documentation.

**Comment by TheDarrenS** [comment]
Hi Nosvagor.

Well, got the issue sorted, I was the rustup nightly build causing the issue.

Everything installed with no issues. Just at a loss how to initiate your dotfiles on startup?

Do not think I missed anything.

D..



> hmm, looks like a failure to build paru for some reason.
> 
> these dotfiles are old. I haven't updated in quite some time as my new work wouldn't allow me to use my Linux machine.
> 
> I would not suggest following my instructions as of now to try and replicate what I have, probably multiple issues.
> 
> If anything, use these reference to understand what tools you might need yourself and follow the relevant projects documentation.

**Comment by cogikyo** [comment]
hyprland is what you need to start next (or any window manager & compositor). 

I use sddm (step 5) to auto start it, but you can also just run the hyprland command itself.
